name: Pulse CI
on:
  push:
    branches-ignore:
    - _**
  pull_request:
  merge_group:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: ubuntu-latest
    container: mtzguido/dev-base
    steps:
      - name: Cleanup
        run: sudo find . -delete

      - run: echo "HOME=/home/user" | sudo tee -a $GITHUB_ENV
      - uses: mtzguido/set-opam-env@master

      # For task pool test
      - run: opam install -t domainslib

      - uses: actions/checkout@master
        id: checkout-fstar
        with:
          path: FStar
          repository: FStarLang/FStar
          ref: fstar1

      - name: Try fetch built F*
        id: cache-fstar
        uses: actions/cache/restore@v4
        with:
          path: FStar
          key: FStar-${{ runner.os }}-${{ runner.arch }}-${{ steps.checkout-fstar.outputs.commit }}

      - name: Build F*
        if: steps.cache-fstar.outputs.cache-hit != 'true'
        run: |
          make -C FStar ADMIT=1 -sj$(nproc)

      - name: Save built F*
        if: steps.cache-fstar.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: FStar
          key: FStar-${{ runner.os }}-${{ runner.arch }}-${{ steps.checkout-fstar.outputs.commit }}

      - run: echo "FSTAR_EXE=$(pwd)/FStar/bin/fstar.exe" | sudo tee -a $GITHUB_ENV

      - uses: actions/checkout@master
        id: checkout-karamel
        with:
          path: karamel
          repository: FStarLang/karamel
          ref: d6607b99477640cb1e5d423d5cbe709d76da61f7

      - name: Try fetch built karamel
        id: cache-karamel
        uses: actions/cache/restore@v4
        with:
          path: karamel
          key: karamel-${{ runner.os }}-${{ runner.arch }}-${{ steps.checkout-fstar.outputs.commit }}-${{ steps.checkout-karamel.outputs.commit }}

      - name: Build karamel (if not cached)
        if: steps.cache-karamel.outputs.cache-hit != 'true'
        run: |
          make -C karamel -sj$(nproc)

      - name: Save built karamel
        if: steps.cache-karamel.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: karamel
          key: karamel-${{ runner.os }}-${{ runner.arch }}-${{ steps.checkout-fstar.outputs.commit }}-${{ steps.checkout-karamel.outputs.commit }}

      - run: echo "KRML_HOME=$(pwd)/karamel" | sudo tee -a $GITHUB_ENV

      - uses: actions/checkout@master
        with:
          path: pulse

      - name: Pulse CI
        id: cistep
        run: . $HOME/.cargo/env && make -C pulse ci -skj$(nproc)
